name: 'Upload asset to a release.'
description: 'Upload asset to specified release or latest one.'
inputs:
  repo:
    description: 'Name of target repo.'
    required: true
  owner:
    description: 'Owner of target repo.'
    required: true
  tag_name:  # name of release
    description: 'tag_name of release, leave it empty if upload to latest one.'
    required: false
  token:
    description: 'Access token to access Github api.'
    required: true
  asset:
    description: 'Asset to upload, can accept a glob pattern to specified multiple files.'
    required: true
outputs:
  download_urls:
    description: 'Download urls that joint with \n.'
runs:
  using: 'node12'
  main: 'dist/index.js'
